### ISSUE TITLE
Error running R

### ISSUE THREAD

**Issue by mspivakov** [rnakato/docker_singlecell#1]
Hello! I find your container really helpful, as a few of these packages are a real pain to install. The singularity container has installed without errors, however, when I try to execute it, I get:

$ singularity exec rnakato_singlecell_jupyter.img R
ERROR: ld.so: object '/apps/rcs-setxattr-replacement/rcs-setxattr-replacement/libc-setxattr-shim.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/rcs-tmpfile-replacement/rcs-tmpfile-replacement/libc-replaced-tmpnam.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/rcs-tmpfile-replacement/rcs-tmpfile-replacement/libc-replaced-tmpfile.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/rcs-setxattr-replacement/rcs-setxattr-replacement/libc-setxattr-shim.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/rcs-tmpfile-replacement/rcs-tmpfile-replacement/libc-replaced-tmpnam.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/rcs-tmpfile-replacement/rcs-tmpfile-replacement/libc-replaced-tmpfile.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/rcs-setxattr-replacement/rcs-setxattr-replacement/libc-setxattr-shim.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/rcs-tmpfile-replacement/rcs-tmpfile-replacement/libc-replaced-tmpnam.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
ERROR: ld.so: object '/apps/rcs-tmpfile-replacement/rcs-tmpfile-replacement/libc-replaced-tmpfile.so' from LD_PRELOAD cannot be preloaded (cannot open shared object file): ignored.
Fatal error:  'R_TempDir' を作成することができません 

My understanding is that I have some permissions issue with R_TempDir. Do you have any suggestions on how this could be fixed? Many thanks!

**Comment by rnakato** [comment]
I am sorry I didn't notice your question. Do you use the LD_PRELOAD variable in your environment? Or, did you try to install the R package in the singularity image?
