### ISSUE TITLE
Request: can you add miloR?

### ISSUE THREAD

**Issue by bingy007** [rnakato/docker_singlecell#10]
Hi,

Thanks a lot for building this super helpful container! Can you add miloR for different abundance testing?
https://github.com/MarioniLab/miloR
Thanks a lot

Best,
B

**Comment by rnakato** [comment]
Hi bingy007, we will consider including miloR in the next update.

**Comment by rnakato** [comment]
Hi bingy007, we added miloR in the latest version 1.8.0.

**Comment by bingy007** [comment]
Many thanks! @rnakato
