### ISSUE TITLE
how to update the R version in singularity ?

### ISSUE THREAD

**Issue by cmulittlechild** [rnakato/docker_singlecell#12]
I am working on HPC, only supports singularity.

Currently, there are many R packages rely on R 4.4, but in latest singularity(sortcake.3.0) is R 4.3.

And the R is use the root one but not the virtual env, so i am afraid if i change the R version from 4.3 to 4.4 manually,  it would damage the R env.

Now, i have transform the sif to sandbox, could you tell me how to change the R version on right way? 

Thanks very much!

**Comment by rnakato** [comment]
The right way would be to create a new docker image using our shortcake as the base image, then you can update the version of R by yourself. Then you can create a singularity file from the docker image. Singularity + sandbox is also fine as long as the packages you're using don't show an error.
