### ISSUE TITLE
Error loading Seurat only

### ISSUE THREAD

**Issue by nannabarnkob** [rnakato/docker_singlecell#2]
Hello, 

I have started the container in an R session using `singularity exec [--nv] rnakato_singlecell_jupyter.sif R`
While in R, I can load all packages of interest without errors, except Seurat. I get the following error: 

```
> library(Seurat)
Error: package or namespace load failed for ‘Seurat’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/usr/local/lib/R/site-library/igraph/libs/igraph.so':
  libmkl_rt.so.1: cannot open shared object file: No such file or directory
```

I tried installing Seurat with `install.packages("Seurat")` without luck.

The end of my trace looks like this: 
```
** byte-compile and prepare package for lazy loading
Error in dyn.load(file, DLLpath = DLLpath, ...) :
  unable to load shared object '/usr/local/lib/R/site-library/igraph/libs/igraph.so':
  libmkl_rt.so.1: cannot open shared object file: No such file or directory
Calls: <Anonymous> ... asNamespace -> loadNamespace -> library.dynam -> dyn.load
Execution halted
ERROR: lazy loading failed for package ‘Seurat’
* removing ‘/home/people/nanbar/R/x86_64-pc-linux-gnu-library/4.1/Seurat’

The downloaded source packages are in
        ‘/tmp/Rtmp7hgrKi/downloaded_packages’
Warning message:
In install.packages("Seurat") :
  installation of package ‘Seurat’ had non-zero exit status
```

Is there any way to fix this? I would very much like to run Seurat using your container. 

Thanks a lot! 
Nanna

**Comment by rnakato** [comment]
Recently I updated this image to version 2022.03 so could you make the sif image using the latest version and try it again? In my environment, there is no error to load Seurat.

**Comment by nannabarnkob** [comment]
I downloaded and built the image using the newest version the night before my message, so I don't think it will be the solution. Nevertheless, thank you for getting back to me.

**Comment by rnakato** [comment]
I cannot reproduce your error in my environment using the latest image. `library(Seurat) ` and `install.packages("Seurat")` did not make any errors. So it would be related to your environment, for example, already installed packages in your `~/R` directory in your PC, or cache for singularity sandbox. I also think it would be worth to try building the image again.
