### ISSUE TITLE
Failed to attach native file to docker file

### ISSUE THREAD

**Issue by XiangyangWang296** [rnakato/docker_singlecell#3]
Hi, Thanks for your great docker image.
I have got it in server by run command as follows as:
`docker run -it --name notebook-server -p 1997:8888 -v /home/wangxy/seqdata/v8/:/opt/work rnakato/singlecell_jupyter jupyternotebook.sh`

'/home/wangxy/seqdata' is my work directory, saving data to be analyzed.

But my problem is that   `-v /home/wangxy/seqdata/v8/:/opt/work` didn't seem to work. 

The jupyter interface (browser) just present files in /opt/work.

I can't find my work directory in jupyter. 

Could you tell me where the mistake is? Thanks.

**Comment by rnakato** [comment]
The working directory is `/work` so `/opt/work` cannot be accessed from the jupyter command. I'm sorry for the inconvenience.
Please try the mount option `-v /home/wangxy/seqdata/v8/:/work/mnt` and check `mnt/` directory in the notebook.

**Comment by XiangyangWang296** [comment]
I really need to learn more about docker, like how to set up self-defined dockerfile...
And Thanks! 
`-v /home/wangxy/seqdata/v8/:/work/mnt` works!
