### ISSUE TITLE
Error opening jupyter-lab

### ISSUE THREAD

**Issue by XiangyangWang296** [rnakato/docker_singlecell#4]
Hi~
I had used your great image for several months, mainly entering by jupyter-notebook.

Since jupyter-lab has more convenience, I tried to install jupyter-lab to replace notebook by the following code:
```
sudo docker exec -it f62de1534803 /bin/bash
pip install jupyter-lab
touch jupyter-lab.sh
sudo chmod 777 jupyter-lab.sh
  ( #!/bin/bash
    jupyter-lab --allow-root --no-browser --ip "（my ip address）" --port 9999 )

sudo docker run -it --name jupyterlab -p 9999:8888 -v /home/wangxy/seqdata/:/work/mnt rnakato/singlecell_jupyter jupyterlab.sh
```
Then I got the following error

**OSError: [Errno 99] Cannot assign requested address**

I tried to use the --ip=0.0.0.0 option to launch jupyter. But then I checked the /etc/hosts file to add my host name and address. But this error still existed.

Could you tell me anything went wrong?

**Comment by rnakato** [comment]
Hi XiangyangWang296,

- JupyterLab is installed in this image so you don't have to install it again.
- In my environment, I could launch JupyterLab as follows. I think the problem may be due to your command or environment (possibly IP address or port forwarding). Please check that.

```
$ docker run -it -p 9999:8888 rnakato/singlecell_jupyter jupyter-lab --allow-root --no-browser
[I 2022-06-09 02:59:52.932 ServerApp] jupyterlab | extension was successfully linked.
[W 2022-06-09 02:59:52.956 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-06-09 02:59:52.956 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2022-06-09 02:59:52.957 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[I 2022-06-09 02:59:52.997 ServerApp] Writing Jupyter server cookie secret to /root/.local/share/jupyter/runtime/jupyter_cookie_secret
[I 2022-06-09 02:59:55.928 ServerApp] nbclassic | extension was successfully linked.
[I 2022-06-09 02:59:56.495 ServerApp] nbclassic | extension was successfully loaded.
[I 2022-06-09 02:59:56.496 LabApp] JupyterLab extension loaded from /opt/conda/lib/python3.9/site-packages/jupyterlab
[I 2022-06-09 02:59:56.496 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[I 2022-06-09 02:59:56.499 ServerApp] jupyterlab | extension was successfully loaded.
[I 2022-06-09 02:59:56.500 ServerApp] Serving notebooks from local directory: /work
[I 2022-06-09 02:59:56.500 ServerApp] Jupyter Server 1.13.5 is running at:
[I 2022-06-09 02:59:56.500 ServerApp] http://0c2c83021282:8888/lab?token=38547f83753ae992baa31b2b67be47151644de1bd94d1145
[I 2022-06-09 02:59:56.500 ServerApp]  or http://127.0.0.1:8888/lab?token=38547f83753ae992baa31b2b67be47151644de1bd94d1145
[I 2022-06-09 02:59:56.500 ServerApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 2022-06-09 02:59:56.514 ServerApp]

    To access the server, open this file in a browser:
        file:///root/.local/share/jupyter/runtime/jpserver-1-open.html
    Or copy and paste one of these URLs:
        http://0c2c83021282:8888/lab?token=38547f83753ae992baa31b2b67be47151644de1bd94d1145
     or http://127.0.0.1:8888/lab?token=38547f83753ae992baa31b2b67be47151644de1bd94d1145
```

**Comment by XiangyangWang296** [comment]
Thank you, rnakato.
It works after I assigning ip address in jupyter server config file.
Now I could run it as follows.
`sudo docker run -it --name jupyterlab -p 1995:8888 -v /home/wangxy/seqdata/:/work/mnt rnakato/singlecell_jupyter jupyter-lab --allow-root --no-browser`


Another question, since I have made some alternation in running container.
These change include installing some packages as follows and adding some bash files(such jupyterlab.sh)...

############################
#####   New packages  #########
############################
install.packages('chameleon');install.packages('ComplexHeatmap');install.packages('aplot')
!pip install squidpy;!pip install metacells; 
!conda install -c conda-forge jupyter_contrib_nbextensions -y;!conda install -c conda-forge jupyter_nbextensions_configurator -y 

So how could I save these change as a new image? And I don't have to run commands for making these change again when I create a new container.

Should I change dockerfile to achieve this goal? Or in some more easy way?

**Comment by rnakato** [comment]
You can make your own image by making a Dockerfile that uses my image as a base image. See manual:
https://docs.docker.com/develop/develop-images/dockerfile_best-practices/
