### ISSUE TITLE
ImportError for cellrank 

### ISSUE THREAD

**Issue by qisun2** [rnakato/docker_singlecell#5]
Using your latest docker image rnakato/singlecell_jupyter:2022.08,  I got an error message when "import cellrank as cr".

ImportError: cannot import name 'Iterable' from 'collections' (/opt/conda/envs/CellRank/lib/python3.10/collections/__init__.py)

I googled this error.  The reason is "the Iterable abstract class was removed from collections in Python 3.10". You might have to set Python to 3.9?

Qi

**Comment by rnakato** [comment]
Hi Qi,
Thank you for the report. I modified the `2022.08` image to use Python3.9 for CellRank. Could you pull the image again and try CellRank?

**Comment by qisun2** [comment]
It works now. Thank your for the prompt fix, and for maintaining this very useful resource!
