### ISSUE TITLE
  nbconvert failed: module 'jinja2' has no attribute 'Markup'

### ISSUE THREAD

**Issue by JiantaoShi** [rnakato/docker_singlecell#6]
This is a great docker image. But in the latest version (v1.1.0), Jupiter failed to convert notebook to html files. We thus get the following error: nbconvert failed: module 'jinja2' has no attribute 'Markup'

**Comment by JiantaoShi** [comment]
<img width="685" alt="shortcase_Jupyter_error" src="https://user-images.githubusercontent.com/5055792/210681981-1412b90f-dc61-4148-ab2a-161f2f785a95.png">

**Comment by JiantaoShi** [comment]
<img width="860" alt="shortcase_Jupyter_error2" src="https://user-images.githubusercontent.com/5055792/210682198-e7eee7c2-c785-46f0-8b1a-571bdc49e47b.png">

**Comment by rnakato** [comment]
Hi JiantaoShi,
I updated ShortCake v1.1.1 in which jinja2 is downgraded to v3.0.3. Could you try it?

reference: https://github.com/microsoft/vscode-jupyter/issues/9468

**Comment by JiantaoShi** [comment]
Thanks, the issues have been solved!

Jiantao
