### ISSUE TITLE
Request: Cellrank update & rapids_singlecell addition

### ISSUE THREAD

**Issue by nagendraKU** [rnakato/docker_singlecell#9]
Hi @rnakato,

Thanks a lot for the really useful docker image! I would like to submit the following requests for the next release of Shortcake as I cannot build Docker images on my HPC system.

1. Update Cellrank to version 2, which is a major change from v1.
2. Include rapids_singlecell (https://github.com/scverse/rapids_singlecell) as a GPU-accelerated augmentation of Scanpy.

Many thanks for your time and effort in maintaining this resource!

**Comment by eijynagai** [comment]
Hi @nagendraKU,

I'm part of the ShortCake support team. Thank you for sharing your valuable suggestions with us. 
We appreciate your input and will strongly consider incorporating your ideas into our next release. Stay tuned for updates!

Best regards,
Eijy

**Comment by rnakato** [comment]
Hi @nagendraKU,

I've updated ShortCake (v1.7.0) in which Cellrank2 and rapids_singlecell are available.
I've briefly confirmed they can be imported in the jupyter notebook, but let me know if there are any problems.
